# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_7Z "")
set(CPACK_BINARY_BUNDLE "")
set(CPACK_BINARY_CYGWIN "")
set(CPACK_BINARY_DEB "")
set(CPACK_BINARY_DRAGNDROP "")
set(CPACK_BINARY_FREEBSD "")
set(CPACK_BINARY_IFW "")
set(CPACK_BINARY_NSIS "")
set(CPACK_BINARY_NUGET "")
set(CPACK_BINARY_OSXX11 "")
set(CPACK_BINARY_PACKAGEMAKER "")
set(CPACK_BINARY_PRODUCTBUILD "")
set(CPACK_BINARY_RPM "")
set(CPACK_BINARY_STGZ "")
set(CPACK_BINARY_TBZ2 "")
set(CPACK_BINARY_TGZ "")
set(CPACK_BINARY_TXZ "")
set(CPACK_BINARY_TZ "")
set(CPACK_BINARY_WIX "")
set(CPACK_BINARY_ZIP "")
set(CPACK_BUILD_SOURCE_DIRS "/home/midhul/jiffy;/home/midhul/jiffy/cmake-modules")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_GENERATOR "TGZ;DEB;RPM")
set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY "TRUE")
set(CPACK_INSTALL_CMAKE_PROJECTS "/home/midhul/jiffy/cmake-modules;Jiffy;ALL;/")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "/home/midhul/jiffy/cmake-modules")
set(CPACK_MONOLITHIC_INSTALL "TRUE")
set(CPACK_NSIS_DISPLAY_NAME "jiffy 0.1.0")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "jiffy 0.1.0")
set(CPACK_OUTPUT_CONFIG_FILE "/home/midhul/jiffy/cmake-modules/CPackConfig.cmake")
set(CPACK_OUTPUT_FILE_PREFIX "packages")
set(CPACK_PACKAGE_ARCHITECTURE "amd64")
set(CPACK_PACKAGE_CONTACT "anurag.khandelwal@yale.edu")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/home/midhul/jiffy/cmake-modules/README.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Jiffy")
set(CPACK_PACKAGE_FILE_NAME "jiffy-0.1.0-linux-amd64")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "jiffy 0.1.0")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "jiffy 0.1.0")
set(CPACK_PACKAGE_NAME "jiffy")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Anurag Khandelwal")
set(CPACK_PACKAGE_VERSION "0.1.0")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "1")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_PROJECT_CONFIG_FILE "/home/midhul/jiffy/cmake-modules/jiffy-package.cmake")
set(CPACK_RESOURCE_FILE_LICENSE "/home/midhul/jiffy/LICENSE")
set(CPACK_RESOURCE_FILE_README "/usr/local/share/cmake-3.14/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/home/midhul/jiffy/LICENSE")
set(CPACK_RPM_CHANGELOG_FILE "/home/midhul/jiffy/ChangeLog.txt")
set(CPACK_RPM_PACKAGE_GROUP "Development/Libraries")
set(CPACK_RPM_PACKAGE_LICENSE "BSD")
set(CPACK_RPM_PACKAGE_URL "")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_7Z "")
set(CPACK_SOURCE_CYGWIN "")
set(CPACK_SOURCE_GENERATOR "TGZ;ZIP")
set(CPACK_SOURCE_IGNORE_FILES "/\\.git/;\\.swp$;\\.#;/#;\\.*~;cscope\\.*;/[Bb]uild[.+-_a-zA-Z0-9]*/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/midhul/jiffy/cmake-modules/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "jiffy-0.1.0")
set(CPACK_SOURCE_RPM "")
set(CPACK_SOURCE_TBZ2 "")
set(CPACK_SOURCE_TGZ "")
set(CPACK_SOURCE_TOPLEVEL_TAG "source")
set(CPACK_SOURCE_TXZ "")
set(CPACK_SOURCE_TZ "")
set(CPACK_SOURCE_ZIP "")
set(CPACK_SYSTEM_NAME "linux")
set(CPACK_TOPLEVEL_TAG "linux")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/midhul/jiffy/cmake-modules/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
